name: Sanity tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1,15 * *'

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.17
          - stable-2.18
          - stable-2.19
          - devel
    runs-on: ubuntu-24.04
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1.17
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          pull-request-change-detection: false
